/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author Windows 10
 */
public class penampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form penampilGambar
     */
    public penampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        glassfishBTA = new javax.swing.JButton();
        javaeeBTA = new javax.swing.JButton();
        postgresalBTA = new javax.swing.JButton();
        exitBTA = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        glassfishLB = new javax.swing.JLabel();
        javaeeLB = new javax.swing.JLabel();
        postgreSQL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        glassfishBTA.setText("Glassfish");
        glassfishBTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glassfishBTAActionPerformed(evt);
            }
        });
        buttonPanel.add(glassfishBTA);

        javaeeBTA.setText("JavaEE");
        javaeeBTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaeeBTAActionPerformed(evt);
            }
        });
        buttonPanel.add(javaeeBTA);

        postgresalBTA.setText("PostgreSQL");
        postgresalBTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgresalBTAActionPerformed(evt);
            }
        });
        buttonPanel.add(postgresalBTA);

        exitBTA.setText("Exit");
        exitBTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTAActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBTA);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.CENTER);

        imagePanel.setLayout(new java.awt.CardLayout());

        glassfishLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glassfishLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/glassFish.jpg"))); // NOI18N
        imagePanel.add(glassfishLB, "0");

        javaeeLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaeeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JavaEE.jpg"))); // NOI18N
        imagePanel.add(javaeeLB, "1");

        postgreSQL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postgreSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/postgree.jpg"))); // NOI18N
        imagePanel.add(postgreSQL, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void glassfishBTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glassfishBTAActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_glassfishBTAActionPerformed

    private void javaeeBTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaeeBTAActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_javaeeBTAActionPerformed

    private void postgresalBTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgresalBTAActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2"); // TODO add your handling code here:
    }//GEN-LAST:event_postgresalBTAActionPerformed

    private void exitBTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTAActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penampilGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBTA;
    private javax.swing.JButton glassfishBTA;
    private javax.swing.JLabel glassfishLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton javaeeBTA;
    private javax.swing.JLabel javaeeLB;
    private javax.swing.JLabel postgreSQL;
    private javax.swing.JButton postgresalBTA;
    // End of variables declaration//GEN-END:variables
}
